# -*- coding: utf-8 -*-
"""Demand Calculation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQIb7dc5Rdu63pJUT1oXXLofTka1Rujh
"""

def get_kc(day):
    if day <= 15:
        return 0.5
    elif day <= 30:
        return 0.8
    elif day <= 45:
        return 1.2
    elif day <= 75:
        return 1.3
    elif day <= 90:
        return 1.2
    elif day <= 105:
        return 1.1
    else:
        return 0.7

import math
from datetime import datetime

def calculate_net_radiation(Tmin, Tmax, ea, lat_deg, date_str, elevation_m):
    """
    Calculates Net Radiation (Rn) based on FAO-56 Penman-Monteith equations.

    Parameters:
    Tmin (float): Minimum daily temperature (Celsius)
    Tmax (float): Maximum daily temperature (Celsius)
    ea (float): Actual vapor pressure (kPa)
    lat_deg (float): Latitude in decimal degrees (positive for Northern, negative for Southern)
    date_str (str): Date in 'YYYY-MM-DD' format
    elevation_m (float): Altitude/elevation above sea level (meters)
    k_Rs (float): Empirical coefficient for Hargreaves (default 0.16 for interior)

    Returns:
    float: Net radiation (Rn) in mm/day
    """

    # 1. Calculate Day of the Year (J)
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')
    J = date_obj.timetuple().tm_yday # Day between 1 and 365/366

    # 2. Convert Latitude to Radians
    # Sri Lanka is located in the Northern Hemisphere, (phi >0)
    phi = (math.pi / 180) * lat_deg # Radians = (pi/180) * decimal degrees

    # 3. Calculate Inverse Relative Distance Earth-Sun (d_r)
    # Formula: d_r = 1 + 0.033 * cos((2 * pi / 365) * J)
    d_r = 1 + 0.033 * math.cos((2 * math.pi / 365) * J)

    # 4. Calculate Solar Declination (delta)
    # Formula: delta = 0.409 * sin((2 * pi / 365) * J - 1.39)
    delta = 0.409 * math.sin((2 * math.pi / 365) * J - 1.39)

    # 5. Calculate Sunset Hour Angle (omega_s)
    # Formula: omega_s = arccos[-tan(phi) * tan(delta)]
    # Ensure argument to acos is within [-1, 1]
    arg_acos = -math.tan(phi) * math.tan(delta)
    if arg_acos > 1:
        arg_acos = 1
    elif arg_acos < -1:
        arg_acos = -1
    omega_s = math.acos(arg_acos)

    # 6. Calculate Extraterrestrial Radiation (R_a)
    # G_sc (Solar Constant) = 0.0820 MJ m-2 min-1
    G_sc = 0.0820
    # Formula: R_a = (24 * 60 / pi) * G_sc * d_r * [omega_s * sin(phi) * sin(delta) + cos(phi) * cos(delta) * sin(omega_s)]
    R_a = (24 * 60 / math.pi) * G_sc * d_r * (
        omega_s * math.sin(phi) * math.sin(delta) +
        math.cos(phi) * math.cos(delta) * math.sin(omega_s)
    )

    # 7. Calculate Solar Radiation (R_s) using Hargreaves formula
    # Formula: R_s = k_RS * R_a * sqrt(Tmax - Tmin)
    temp_diff = Tmax - Tmin

    k_Rs=0.16  # interior region in Sri Lanka
    R_s = k_Rs * R_a * math.sqrt(temp_diff)

    # 8. Calculate Clear-Sky Radiation (R_so)
    # Formula: R_so = (0.75 + 2 * 10^-5 * z) * R_a

    R_so = (0.75 + 2e-5 * elevation_m) * R_a

    # 9. Calculate Net Shortwave Radiation (R_ns)
    # Albedo (alpha) approx 0.23 for grass reference
    albedo = 0.23
    # Formula: R_ns = (1 - alpha) * R_s
    R_ns = (1 - albedo) * R_s

    # 10. Calculate Net Longwave Radiation (R_nl)
    # Stefan-Boltzmann constant (sigma) = 4.903e-9 MJ K-4 m-2 day-1
    sigma = 4.903e-9

    # Convert temperatures to Kelvin for R_nl
    Tmax_K = Tmax + 273.16
    Tmin_K = Tmin + 273.16

    # Formula components:
    # Mean absolute temp: (Tmax_K^4 + Tmin_K^4) / 2
    mean_temp_term = (math.pow(Tmax_K, 4) + math.pow(Tmin_K, 4)) / 2
    # Vapor pressure effect: (0.34 - 0.14 * sqrt(e_a))
    vapor_term = 0.34 - 0.14 * math.sqrt(ea)
    # Cloudiness effect: (1.35 * (R_s / R_so) - 0.35)
    cloud_term = 1.35 * (R_s / R_so) - 0.35

    # Combine R_nl formula
    R_nl = sigma * mean_temp_term * vapor_term * cloud_term

    # 11. Calculate final Net Radiation (R_n) in MJ/m2/day
    # Formula: R_n_MJ = R_ns - R_nl
    R_n_MJ = R_ns - R_nl

    # 12. Convert to mm/day [ADDED SECTION]
    # Latent heat of vaporization (lambda) = 2.45 MJ/kg
    latent_heat = 2.45
    R_n_mm = R_n_MJ / latent_heat

    return R_n_mm

def get_elevation(lat, lon):
    try:# some times getting request can be failed to find the elevation , At that time all programme will fail
        url = f"https://api.open-elevation.com/api/v1/lookup?locations={lat},{lon}"
        res = requests.get(url, timeout=5)
        return res.json()["results"][0]["elevation"]
    except:
        return 500  # fallback this elevation of university of peradeniya

import requests
import math
from datetime import datetime

# ---------------- USER INPUT ----------------
api_key = "3ed62f8faf22430f54666b224f9da42d"
lat = 7.2542
lon = 80.5967

planting_date = datetime(2026, 4, 1)

#API data can predict upto 5 days in future
target_date = datetime(2026, 5, 24)

A = 1000      # area (m²)
CE = 0.7      # canal efficiency

# -------------------------------------------

# ----------- GET WEATHER DATA ---------------
url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}&units=metric"
data = requests.get(url).json()

T_list, RH_list, wind_list, rain_list = [], [], [], []

for entry in data["list"]:
    if target_date.strftime("%Y-%m-%d") in entry["dt_txt"]:
        T_list.append(entry["main"]["temp"])
        RH_list.append(entry["main"]["humidity"])
        wind_list.append(entry["wind"]["speed"])
        rain_list.append(entry.get("rain", {}).get("3h", 0))

#API data can predict upto 5 days in future
if len(T_list) == 0:
    raise ValueError("No forecast data available for selected date (API limit ~5 days)")

Tmean = sum(T_list)/len(T_list)
RHmean = sum(RH_list)/len(RH_list)
u10 = sum(wind_list)/len(wind_list)
rain = sum(rain_list)
Tmax=max(T_list)
Tmin=min(T_list)

#elevation_m (elevation for the cordinates)
#url = f"https://api.open-elevation.com/api/v1/lookup?locations={lat},{lon}"
#data = requests.get(url).json()
#elevation_m = data["results"][0]["elevation"]

elevation_m = get_elevation(lat, lon)

# Convert wind to 2m
u2 = u10 * 0.748


# Vapor pressure
es = 0.6108 * math.exp((17.27*Tmean)/(Tmean+237.3))
ea = (RHmean/100) * es

# Delta
Delta = (4098 * es)/((Tmean+237.3)**2)

# Psychrometric constant
gamma = 0.0665 # atmospheric pressure assume sea level ,p= 101.3kPa

# Net radiation (simplified using Rs)
Rn = calculate_net_radiation(Tmin, Tmax, ea, lat, target_date.strftime("%Y-%m-%d"), elevation_m) # not completeed

# Wind function
fu = 0.27 * (1 + u2/100) # check the units

# Weight factor
W = Delta / (Delta + gamma)

# ET0
ET0 = (W * Rn) + ((1-W) * fu * (es - ea))

# ----------- CROP COEFFICIENT --------------
days_after_planting = (target_date - planting_date).days
Kc = get_kc(days_after_planting)

# ----------- WATER REQUIREMENT -------------
CWR = Kc * ET0

# Effective rainfall (simple assumption)
Reff = 0.8 * rain

# Irrigation demand
demand = max(0, ((CWR - Reff) * A) / CE)

# ----------- OUTPUT ------------------------
print("Date:", target_date.date())
print("Days after planting:", days_after_planting)
print("Kc:", Kc)
print("Tmean:", round(Tmean,2), "°C")
print("RHmean:", round(RHmean,2), "%")
print("Elevation of cordinates", round(elevation_m,2), "m")
print("u10:", round(u10,2), "m/s")
print("ET0:", round(ET0,2), "mm/day")
print("CWR:", round(CWR,2), "mm/day")
print("Rain:", round(rain,2), "mm")
print("Irrigation Demand:", round(demand,2), "liters/day")