# -*- coding: utf-8 -*-
"""Moisture Threshold level .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZuFcmNOjVVW9GzwO2HgL8cGLua_TkJ25
"""

# Data extracted from Image 1: Soil water thresholds
SOIL_DATA = {
    "Sand": {"FC": 10, "PWP": 4},
    "Loamy sand": {"FC": 16, "PWP": 7},
    "Sandy loam": {"FC": 21, "PWP": 9},
    "Loam": {"FC": 27, "PWP": 12},
    "Silt loam": {"FC": 30, "PWP": 15},
    "Sandy clay loam": {"FC": 36, "PWP": 16},
    "Sandy clay": {"FC": 32, "PWP": 18},
    "Clay loam": {"FC": 29, "PWP": 18},
    "Silty clay loam": {"FC": 28, "PWP": 15},
    "Silty clay": {"FC": 40, "PWP": 20},
    "Clay": {"FC": 40, "PWP": 22}
}

# Data extracted from Image 2: Crop management allowed depletion (MAD)
# Note: For ranges, the lower bound has been used to remain conservative for water safety.
CROP_DATA = {
    "Cotton": {"MAD": 0.65},
    "Barley and oats": {"MAD": 0.55},
    "Maize": {"MAD": 0.50},
    "Sorghum": {"MAD": 0.50},
    "Rice": {"MAD": 0.20},
    "Beans": {"MAD": 0.45},
    "Soybeans": {"MAD": 0.50},
    "Alfalfa": {"MAD": 0.50},
    "Cool season – Turf grass": {"MAD": 0.40},
    "Warm season – Turf grass": {"MAD": 0.50},
    "Citrus": {"MAD": 0.50},
    "Walnut orchard": {"MAD": 0.50},
    "Carrots": {"MAD": 0.35},
    "Cantaloupes/watermelons": {"MAD": 0.40},
    "Lettuce": {"MAD": 0.30},
    "Onions": {"MAD": 0.30},
    "Potatoes": {"MAD": 0.65},
    "Sweet peppers": {"MAD": 0.30},
    "Cucumbers": {"MAD": 0.50}
}

def calculate_moisture_threshold(soil_texture: str, crop_type: str) -> float:
    """
    Calculates the Moisture Threshold Level using the equation:
    Threshold = FC - [MAD * (FC - PWP)]
    """
    if soil_texture not in SOIL_DATA or crop_type not in CROP_DATA:
        raise ValueError("Invalid soil texture or crop type provided.")

    fc = SOIL_DATA[soil_texture]["FC"]
    pwp = SOIL_DATA[soil_texture]["PWP"]
    mad = CROP_DATA[crop_type]["MAD"]

    # Core equation
    threshold = fc - (mad * (fc - pwp))

    return round(threshold, 2)

